apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
spec:
  replicas: {{ .Values.castservice.replicas }}  # Utilisation de la valeur définie dans values.yaml
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: {{ .Values.castservice.image }}  # Utilisation de la valeur définie dans values.yaml
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: postgresql://cast_db_username:cast_db_password@cast-db-service/cast_db_dev
          command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
spec:
  type: NodePort
  selector:
    app: cast-service
  ports:
    - protocol: TCP
      port: {{ .Values.castservice.port }}
      targetPort: 8000

