apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cast-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path # Update this
  resources:
    requests:
      storage: 1Gi # Match this with the storage size in the StatefulSet

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path # Update this
  resources:
    requests:
      storage: 1Gi # Match this with the storage size in the StatefulSet
